### PR TITLE
Disambiguate buffer names

### PR DESCRIPTION
**Pull request by chunkhang**
We keep track of buffer `head` and `tail`, which is basically the
directory and basename. We start off with just the `tail` as the buffer
`name`. If there are multiple occurrences of the same `name`, we prepend
`tail` with the last element from `head`. We keep using more and more
elements from `head` until all buffer names are unique. New buffers are
not included in the disambiguate process.

### CODE REVIEW

**Comment by chunkhang** [comment]
In regards to #25

**Comment by chunkhang** [comment]
> Just tested this and it works perfect +1 it is just that the `update` grows too long and the code is not that readable. Maybe we can at least break these additions into functions to that we can then more easily refactor them, what do you think @chunkhang?

Sure, I'll do that. However, after this, we should really be looking at reworking how we store and manage the existing buffer list. Using the right approach should solve #24.

**Comment by bagrat** [comment]
> However, after this, we should really be looking at reworking how we store and manage the existing buffer list.

totally 👍

**Comment by bagrat** [comment]
@chunkhang I have created a separate issue for the refactor https://github.com/bagrat/vim-buffet/issues/32, so let's not block this feature and merge it right away.

**Pull request merged**
